version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: pagesAlvin200@237
      MYSQL_DATABASE: projet9
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - spring-boot-network

  patient:
    build: .
    container_name: patient
    ports:
      - "9002:9002"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/projet9?createDatabaseIfnotExist=true&useSSl=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: pagesAlvin200@237
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - mysql
    networks:
      - spring-boot-network

networks:
  spring-boot-network:

volumes:
  mysql_data:
