spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: patient
          uri: http://patient:9002
          predicates:
            - Path=/patients/

        - id: front
          uri: http://front:9004
          predicates:
            - Path=/fronts/

        - id: note
          uri: http://note:9005
          predicates:
            - Path=/notes/

        - id: diagnostic
          uri: http://diagnostic:9006
          predicates:
            - Path=/diagnostics/
