spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: patient
          uri: localhost:9002
          predicates:
            - Path=/patients/

        - id: front
          uri: localhost:9004
          predicates:
            - Path=/front/

        - id: note
          uri: localhost:9005
          predicates:
            - Path=/notes/
# jwt:
#   secret: mySecretKey
