version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: pagesAlvin200@237
    #   MONGO_INITDB_DATABASE: projet9MD
    volumes:
      - db_data_mongo:/data/db
      - mongo_config:/data/configdb
    ports:
      - "27017:27017"
    networks:
      - spring-boot-network

  note:
    build: .
    container_name: note
    depends_on:
      - mongodb
    restart: always
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb # Utilisation du nom du service MongoDB
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: projet9MD
    ports:
      - "9005:9005"
    networks:
      - spring-boot-network

networks:
  spring-boot-network:

volumes:
  db_data_mongo:
  mongo_config:
